### ISSUE TITLE
no discord or modrinth/curse profile

### ISSUE THREAD

**Issue by tlaselbat** [borisshoes/fabric-trade#1]
your mods are awesome and id like to follow them closer. ty

**Comment by borisshoes** [comment]
Thank so much for the support! I've been considering putting my mods on Curse/Modrinth for a while. When I update everything to 1.20.6 (or whichever hotfix is out at the time), I'll look into it again. I'll leave the issue open until then.

**Comment by borisshoes** [comment]
Thanks again for your interest in my mods. I am going to be uploading new versions on Modrinth!

[](https://modrinth.com/user/BorisShoes)
[](https://modrinth.com/mod/fabric-trade)
